name: "Rebase one branch on another branch"

on:
  push:
    branches:
      - "main"

jobs:
  update-next:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b" # v4.1.4

      - name: "Update child branch to latest main branch"
        env:
          CHILD_BRANCH: "test"
          BASE_BRANCH: "main"
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.bot"


          git fetch origin ${{ env.CHILD_BRANCH }}
          git branch --force ${{ env.CHILD_BRANCH }} FETCH_HEAD
          git --version

          echo "DEBUGGING GIT LOGS!"
          git log -3

          git rebase ${{ env.BASE_BRANCH }} ${{ env.CHILD_BRANCH }}

          echo "DEBUGGING GIT LOGS!"
          git log -3
          # git push origin "${{ env.CHILD_BRANCH }}"
