name: "Rebase one branch on another branch"

on:
  push:
    branches:
      - "main"

jobs:
  update-next:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b" # v4.1.4


      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3


      - name: "Update child branch to latest main branch"
        env:
          CHILD_BRANCH: "test"
          BASE_BRANCH: "main"
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.bot"

          git fetch origin ${{ env.CHILD_BRANCH }}
          git checkout -B ${{ env.CHILD_BRANCH }} origin/${{ env.CHILD_BRANCH }}
          git --version

          echo "DEBUGGING GIT LOGS!"
          git log -3
          echo ""
          echo ""
          echo ""

          git rebase --rebase-merges origin/${{ env.BASE_BRANCH }}

          echo "DEBUGGING GIT LOGS!"
          git log -3
          # git push origin "${{ env.CHILD_BRANCH }}"
